language: scala
scala:
- 2.12.4
script:
- sbt clean coverage test coverageReport
after_success:
- sbt coverageReport coveralls

services:
  - xvfb
before_script:
- "export DISPLAY=:99.0"
- sleep 3 # give xvfb some time to start

