version: "3.0"

services:
  field:
    build:
      context: ./Field/
      dockerfile: ./Dockerfile
    ports:
      - 9003:9003
    stdin_open: true
    container_name: fieldservice
  fileio:
    build:
      context: ./FileIO/
      dockerfile: ./Dockerfile
    ports:
      - 9004:9004
    stdin_open: true
    container_name: fileioservice
  shutthebox:
    build:
      context: ./
      dockerfile: ./Dockerfile
    stdin_open: true
    container_name: rootservice
    depends_on:
      - field
      - fileio
    environment:
      - DISPLAY=host.docker.internal:0